# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BRAVI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BRAVI
	
  	pod "TinyConstraints"
  	pod "Alamofire"

end
